disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

languageCode: en-us
baseURL: https://ugnelis.github.io

markup:

  # TODO: use Goldmark once it has hrefTargetBlank feature.
  defaultMarkdownHandler: blackFriday

  blackFriday:
    hrefTargetBlank: true
    noreferrerLinks: true

params:
  description: Programming, music and other relevant things
  author: Ugnius Malukas
  name: malukas.lt
  images:
    - icon.png
